Lab2/Models/CalcResult.cs
namespace Lab2.Models
{
    /// <summary>
    /// Результат вычисления
    /// </summary>
    public class CalcResult
    {
        public int FirstValue { get; set; }
        public int SecondValue { get; set; }
        public string Name { get; private set; }
        public string Operation { get; set; }
        public string Result { get; private set; }
        public CalcResult()
        {
            Name = "";
            Result = "";
        }
        public CalcResult(int firstValue, int secondValue, string operation)
        {
            FirstValue = firstValue;
            SecondValue = secondValue;
            Operation = operation;
            Calc();
        } 

        public string Print()
        {
            if(Result == "") Calc();
            return $"{FirstValue} {Operation} {SecondValue} = {Result}";
        }

        private void Calc()
        {
            switch (Operation)
            {
                case "+":
                    {
                        Name = "Add";
                        Result = (FirstValue + SecondValue).ToString();
                        break;
                    }
                case "-":
                    {
                        Name = "Sub";
                        Result = (FirstValue - SecondValue).ToString();
                        break;
                    }
                case "*":
                    {
                        Name = "Mult";
                        Result = (FirstValue * SecondValue).ToString();
                        break;
                    }
                case "/":
                    {
                        Name = "Div";
                        if (SecondValue == 0)
                        {
                            Result = "Attempt to divide by zero";
                        }
                        else
                        {
                            Result = (FirstValue / SecondValue).ToString();
                        }
                        break;
                    }
            }
        }
    }
}

Lab2/Controllers/CalcServiceController.cs
using Microsoft.AspNetCore.Mvc;
using Lab2.Models;
namespace Lab2.Controllers
{
    public class CalcServiceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Manual()
        {
            if(Request.Method == "POST")
            {
                try
                {
                    var model = new CalcResult(int.Parse(HttpContext.Request.Form["FirstValue"]), int.Parse(HttpContext.Request.Form["SecondValue"]), HttpContext.Request.Form["Operation"]);
                    ViewBag.Result = model.Print();
                }
                catch
                {
                    ViewBag.Result = "Invalid input";
                }
                return View("Result");
            }
            return View("ViewWithHtmlHelpers");
        }

        [HttpGet]
        [ActionName("ManualWithSeparateHandlers")]
        public IActionResult ManualWithSeparateHandlersGet()
        {
            return View("ViewWithHtmlHelpers");
        }


        [HttpPost]
        [ActionName("ManualWithSeparateHandlers")]
        public IActionResult ManualWithSeparateHandlersPost()
        {
            try
            {
                var model = new CalcResult(int.Parse(HttpContext.Request.Form["FirstValue"]), int.Parse(HttpContext.Request.Form["SecondValue"]), HttpContext.Request.Form["Operation"]);
                ViewBag.Result = model.Print();
            }
            catch
            {
                ViewBag.Result = "Invalid input";
            }

            return View("Result");
        }

        [HttpGet]
        public IActionResult ModelBindingInParameters()
        {
            return View("ViewWithHtmlHelpers");
        }

        [HttpPost]
        public IActionResult ModelBindingInParameters(int firstValue, string operation, int secondValue)
        {
            if (ModelState.IsValid)
            {
                var model = new CalcResult(firstValue, secondValue, operation);
                ViewBag.Result = model.Print();
            }
            else
            {
                ViewBag.Result = "Invalid input";
            }

            return View("Result");
        }

        [HttpGet]
        public IActionResult ModelBindingInSeparateModel()
        {
            return View("ViewWithTagHelpers");
        }

        [HttpPost]
        public IActionResult ModelBindingInSeparateModel(CalcResult model)
        {
            ViewBag.Result = ModelState.IsValid
                ? model.Print()
                : "Invalid input";

            return View("Result");
        }
    }
}

Lab2/Views/CalcService/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<h1>Form parameters parsing demo</h1>
<ul>
    <li><a asp-controller="CalcService" asp-action="Manual">Manual parsing in single action</a></li>
    <li><a asp-controller="CalcService" asp-action="ManualWithSeparateHandlers">Manual parsing in separate actions</a></li>
    <li><a asp-controller="CalcService" asp-action="ModelBindingInParameters">Model binding (parameters)</a></li>
    <li><a asp-controller="CalcService" asp-action="ModelBindingInSeparateModel">Model binding (separate model)</a></li>
</ul>

Lab2/Views/CalcService/Result.cshtml
@{
    ViewBag.Title = "Result";
}
<h1>Result</h1>
@ViewBag.Result

Lab2/Views/CalcService/ViewWithHtmlHelpers.cshtml
@{
    var action = ViewContext.RouteData.Values["Action"] as string;
    var controller = ViewContext.RouteData.Values["Controller"] as string;
    ViewBag.Title = action;
}
<h1>@action</h1>

@using (Html.BeginForm(action, controller, FormMethod.Post)) {
    @Html.TextBox("FirstValue", "") <br/>
    @Html.DropDownList("Operation", new SelectList(new []{"+", "-", "*", "/"})) <br/>
    @Html.TextBox("SecondValue", "") <br/>
    <input type="submit" value="Submit" />
}

Lab2/Views/CalcService/ViewWithTagHelpers.cshtml
@model Lab2.Models.CalcResult
@{
    var action = ViewContext.RouteData.Values["Action"] as string;
    ViewBag.Title = action;
    var operations = new SelectList( new[] {"+", "-", "*", "/"});
}
<h1>@action</h1>

<form asp-controller="CalcService" asp-action="@action">
    <input asp-for="FirstValue" /><br />
    <select asp-for="Operation" asp-items="operations" ></select><br />
    <input asp-for="SecondValue" /><br />
    <input type="submit" value="Submit" />
</form>

Lab2/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/>
    <title>@ViewBag.Title</title>
</head>
<body>
<header>
    <h2>Backend2</h2>
    <nav><a asp-controller="CalcService" asp-action="Index">Home</a></nav>
</header>
<main>
    @RenderBody()
</main>
<footer>
    <hr/>
    © 2022 - Backend2
</footer>
</body>
</html>